version: "3.8"
services:

  proxy:
    image: nginx:1.21.6-alpine
    restart: always
    depends_on:
      - api
      - client
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    hostname: api
    environment:
      PORT: 3001
    expose:
      - "3001"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U '${POSTGRES_USER}' -d '$POSTGRES_DB' -h '$POSTGRES_HOST'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    hostname: client
    depends_on:
      - api
    expose:
      - "3000"
