version: "3.8"
services:
  solidguard-backend:
    container_name: solidguard-backend
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  redis:
    container_name: redis
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
